ERROR 19-26-2019 16:26:52 Microsoft.EntityFrameworkCore.Database.Connection [9] - An error occurred using the connection to database 'Portal' on server '10.8.0.109'. System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (53): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20

ERROR 19-26-2019 16:26:52 Microsoft.EntityFrameworkCore.Query [9] - An exception occurred in the database while iterating the results of a query for context type 'ScentAir.Payment.Impl.PortalDbContext'.
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (53): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20 System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (53): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20

ERROR 19-26-2019 16:26:52 Microsoft.EntityFrameworkCore.Query [9] - An exception occurred in the database while iterating the results of a query for context type 'ScentAir.Payment.Impl.PortalDbContext'.
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (53): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20 System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (53): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20

ERROR 19-26-2019 16:26:52 Microsoft.EntityFrameworkCore.Database.Connection [9] - An error occurred using the connection to database 'Portal' on server '10.8.0.109'. System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (53): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20

ERROR 19-26-2019 16:26:52 Microsoft.EntityFrameworkCore.Query [9] - An exception occurred in the database while iterating the results of a query for context type 'ScentAir.Payment.Impl.PortalDbContext'.
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (53): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20 System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (53): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20

ERROR 19-26-2019 16:26:52 Microsoft.EntityFrameworkCore.Query [9] - An exception occurred in the database while iterating the results of a query for context type 'ScentAir.Payment.Impl.PortalDbContext'.
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (53): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20 System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (53): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20

INFO  19-29-2019 16:29:19 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully extracted from the HTTP request: {
  "username": "vp1002402",
  "password": "[removed for security reasons]",
  "grant_type": "password",
  "scope": "openid email phone profile offline_access roles"
}. 
DEBUG 19-29-2019 16:29:19 OpenIddict.Server.OpenIddictServerProvider [39] - The token request validation process was partially skipped because the 'client_id' parameter was missing or empty. 
INFO  19-29-2019 16:29:19 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully validated. 
DEBUG 19-29-2019 16:29:19 OpenIddict.Server.OpenIddictServerHandler [39] - The default token request handling was skipped from user code. 
INFO  19-29-2019 16:29:25 OpenIddict.Server.OpenIddictServerProvider [39] - An ad hoc authorization was automatically created and associated with an unknown application: 53edeee3-d359-48ce-b142-c6fc20ae5c8a. 
INFO  19-29-2019 16:29:25 OpenIddict.Server.OpenIddictServerProvider [39] - An ad hoc authorization was automatically created and associated with an unknown application: 53edeee3-d359-48ce-b142-c6fc20ae5c8a. 
DEBUG 19-29-2019 16:29:25 OpenIddict.Server.OpenIddictServerHandler [39] - 'AspNet.Identity.SecurityStamp' was excluded from the access token claims. 
DEBUG 19-29-2019 16:29:25 OpenIddict.Server.OpenIddictServerHandler [39] - 'AspNet.Identity.SecurityStamp' was excluded from the access token claims. 
DEBUG 19-29-2019 16:29:25 OpenIddict.Server.OpenIddictServerHandler [39] - 'fullname' was excluded from the access token claims. 
DEBUG 19-29-2019 16:29:25 OpenIddict.Server.OpenIddictServerHandler [39] - 'fullname' was excluded from the access token claims. 
DEBUG 19-29-2019 16:29:25 OpenIddict.Server.OpenIddictServerHandler [39] - 'email' was excluded from the access token claims. 
DEBUG 19-29-2019 16:29:25 OpenIddict.Server.OpenIddictServerHandler [39] - 'email' was excluded from the access token claims. 
DEBUG 19-29-2019 16:29:25 OpenIddict.Server.OpenIddictServerHandler [39] - 'phone' was excluded from the access token claims. 
DEBUG 19-29-2019 16:29:25 OpenIddict.Server.OpenIddictServerHandler [39] - 'phone' was excluded from the access token claims. 
DEBUG 19-29-2019 16:29:26 OpenIddict.Server.OpenIddictServerHandler [39] - 'AspNet.Identity.SecurityStamp' was excluded from the identity token claims. 
DEBUG 19-29-2019 16:29:26 OpenIddict.Server.OpenIddictServerHandler [39] - 'AspNet.Identity.SecurityStamp' was excluded from the identity token claims. 
DEBUG 19-29-2019 16:29:26 OpenIddict.Server.OpenIddictServerHandler [39] - 'acct' was excluded from the identity token claims. 
DEBUG 19-29-2019 16:29:26 OpenIddict.Server.OpenIddictServerHandler [39] - 'acct' was excluded from the identity token claims. 
INFO  19-29-2019 16:29:26 OpenIddict.Server.OpenIddictServerHandler [39] - The token response was successfully returned: {
  "token_type": "Bearer",
  "access_token": "[removed for security reasons]",
  "expires_in": 3600,
  "refresh_token": "[removed for security reasons]",
  "id_token": "[removed for security reasons]"
}. 
INFO  19-29-2019 16:29:26 OpenIddict.Server.OpenIddictServerHandler [39] - The token response was successfully returned: {
  "token_type": "Bearer",
  "access_token": "[removed for security reasons]",
  "expires_in": 3600,
  "refresh_token": "[removed for security reasons]",
  "id_token": "[removed for security reasons]"
}. 
DEBUG 19-29-2019 16:29:26 OpenIddict.Validation.OpenIddictValidationHandler [39] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-29-2019 16:29:26 OpenIddict.Validation.OpenIddictValidationHandler [39] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-29-2019 16:29:26 OpenIddict.Validation.OpenIddictValidationHandler [25] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-29-2019 16:29:26 OpenIddict.Validation.OpenIddictValidationHandler [25] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-29-2019 16:29:27 OpenIddict.Validation.OpenIddictValidationHandler [39] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-29-2019 16:29:27 OpenIddict.Validation.OpenIddictValidationHandler [39] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-29-2019 16:29:27 OpenIddict.Validation.OpenIddictValidationHandler [39] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-29-2019 16:29:27 OpenIddict.Validation.OpenIddictValidationHandler [39] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-29-2019 16:29:27 OpenIddict.Validation.OpenIddictValidationHandler [34] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-29-2019 16:29:27 OpenIddict.Validation.OpenIddictValidationHandler [34] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-29-2019 16:29:27 OpenIddict.Validation.OpenIddictValidationHandler [34] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-29-2019 16:29:27 OpenIddict.Validation.OpenIddictValidationHandler [34] - AuthenticationScheme: Bearer was successfully authenticated. 
INFO  19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully extracted from the HTTP request: {
  "username": "vp1002402",
  "password": "[removed for security reasons]",
  "grant_type": "password",
  "scope": "openid email phone profile offline_access roles"
}. 
INFO  19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully extracted from the HTTP request: {
  "username": "vp1002402",
  "password": "[removed for security reasons]",
  "grant_type": "password",
  "scope": "openid email phone profile offline_access roles"
}. 
INFO  19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully extracted from the HTTP request: {
  "username": "vp1002402",
  "password": "[removed for security reasons]",
  "grant_type": "password",
  "scope": "openid email phone profile offline_access roles"
}. 
INFO  19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully extracted from the HTTP request: {
  "username": "vp1002402",
  "password": "[removed for security reasons]",
  "grant_type": "password",
  "scope": "openid email phone profile offline_access roles"
}. 
INFO  19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully extracted from the HTTP request: {
  "username": "vp1002402",
  "password": "[removed for security reasons]",
  "grant_type": "password",
  "scope": "openid email phone profile offline_access roles"
}. 
INFO  19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully extracted from the HTTP request: {
  "username": "vp1002402",
  "password": "[removed for security reasons]",
  "grant_type": "password",
  "scope": "openid email phone profile offline_access roles"
}. 
DEBUG 19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerProvider [39] - The token request validation process was partially skipped because the 'client_id' parameter was missing or empty. 
DEBUG 19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerProvider [39] - The token request validation process was partially skipped because the 'client_id' parameter was missing or empty. 
DEBUG 19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerProvider [39] - The token request validation process was partially skipped because the 'client_id' parameter was missing or empty. 
DEBUG 19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerProvider [39] - The token request validation process was partially skipped because the 'client_id' parameter was missing or empty. 
DEBUG 19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerProvider [39] - The token request validation process was partially skipped because the 'client_id' parameter was missing or empty. 
DEBUG 19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerProvider [39] - The token request validation process was partially skipped because the 'client_id' parameter was missing or empty. 
INFO  19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully validated. 
INFO  19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully validated. 
INFO  19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully validated. 
INFO  19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully validated. 
INFO  19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully validated. 
INFO  19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The token request was successfully validated. 
DEBUG 19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The default token request handling was skipped from user code. 
DEBUG 19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The default token request handling was skipped from user code. 
DEBUG 19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The default token request handling was skipped from user code. 
DEBUG 19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The default token request handling was skipped from user code. 
DEBUG 19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The default token request handling was skipped from user code. 
DEBUG 19-30-2019 16:30:20 OpenIddict.Server.OpenIddictServerHandler [39] - The default token request handling was skipped from user code. 
INFO  19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerProvider [51] - An ad hoc authorization was automatically created and associated with an unknown application: c0e01a4e-0f8b-45f3-aaa9-10317c8c94e4. 
INFO  19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerProvider [51] - An ad hoc authorization was automatically created and associated with an unknown application: c0e01a4e-0f8b-45f3-aaa9-10317c8c94e4. 
INFO  19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerProvider [51] - An ad hoc authorization was automatically created and associated with an unknown application: c0e01a4e-0f8b-45f3-aaa9-10317c8c94e4. 
INFO  19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerProvider [51] - An ad hoc authorization was automatically created and associated with an unknown application: c0e01a4e-0f8b-45f3-aaa9-10317c8c94e4. 
INFO  19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerProvider [51] - An ad hoc authorization was automatically created and associated with an unknown application: c0e01a4e-0f8b-45f3-aaa9-10317c8c94e4. 
INFO  19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerProvider [51] - An ad hoc authorization was automatically created and associated with an unknown application: c0e01a4e-0f8b-45f3-aaa9-10317c8c94e4. 
INFO  19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerProvider [51] - An ad hoc authorization was automatically created and associated with an unknown application: c0e01a4e-0f8b-45f3-aaa9-10317c8c94e4. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'AspNet.Identity.SecurityStamp' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'AspNet.Identity.SecurityStamp' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'AspNet.Identity.SecurityStamp' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'AspNet.Identity.SecurityStamp' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'AspNet.Identity.SecurityStamp' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'AspNet.Identity.SecurityStamp' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'AspNet.Identity.SecurityStamp' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'fullname' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'fullname' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'fullname' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'fullname' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'fullname' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'fullname' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'fullname' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'email' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'email' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'email' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'email' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'email' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'email' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'email' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'phone' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'phone' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'phone' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'phone' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'phone' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'phone' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:28 OpenIddict.Server.OpenIddictServerHandler [51] - 'phone' was excluded from the access token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'AspNet.Identity.SecurityStamp' was excluded from the identity token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'AspNet.Identity.SecurityStamp' was excluded from the identity token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'AspNet.Identity.SecurityStamp' was excluded from the identity token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'AspNet.Identity.SecurityStamp' was excluded from the identity token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'AspNet.Identity.SecurityStamp' was excluded from the identity token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'AspNet.Identity.SecurityStamp' was excluded from the identity token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'AspNet.Identity.SecurityStamp' was excluded from the identity token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'acct' was excluded from the identity token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'acct' was excluded from the identity token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'acct' was excluded from the identity token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'acct' was excluded from the identity token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'acct' was excluded from the identity token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'acct' was excluded from the identity token claims. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - 'acct' was excluded from the identity token claims. 
INFO  19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - The token response was successfully returned: {
  "token_type": "Bearer",
  "access_token": "[removed for security reasons]",
  "expires_in": 3600,
  "refresh_token": "[removed for security reasons]",
  "id_token": "[removed for security reasons]"
}. 
INFO  19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - The token response was successfully returned: {
  "token_type": "Bearer",
  "access_token": "[removed for security reasons]",
  "expires_in": 3600,
  "refresh_token": "[removed for security reasons]",
  "id_token": "[removed for security reasons]"
}. 
INFO  19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - The token response was successfully returned: {
  "token_type": "Bearer",
  "access_token": "[removed for security reasons]",
  "expires_in": 3600,
  "refresh_token": "[removed for security reasons]",
  "id_token": "[removed for security reasons]"
}. 
INFO  19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - The token response was successfully returned: {
  "token_type": "Bearer",
  "access_token": "[removed for security reasons]",
  "expires_in": 3600,
  "refresh_token": "[removed for security reasons]",
  "id_token": "[removed for security reasons]"
}. 
INFO  19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - The token response was successfully returned: {
  "token_type": "Bearer",
  "access_token": "[removed for security reasons]",
  "expires_in": 3600,
  "refresh_token": "[removed for security reasons]",
  "id_token": "[removed for security reasons]"
}. 
INFO  19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - The token response was successfully returned: {
  "token_type": "Bearer",
  "access_token": "[removed for security reasons]",
  "expires_in": 3600,
  "refresh_token": "[removed for security reasons]",
  "id_token": "[removed for security reasons]"
}. 
INFO  19-30-2019 16:30:32 OpenIddict.Server.OpenIddictServerHandler [34] - The token response was successfully returned: {
  "token_type": "Bearer",
  "access_token": "[removed for security reasons]",
  "expires_in": 3600,
  "refresh_token": "[removed for security reasons]",
  "id_token": "[removed for security reasons]"
}. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [34] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [34] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [34] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [34] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [34] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [34] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [34] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [39] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [39] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [39] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [39] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [39] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [39] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [39] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [44] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [44] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [44] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [44] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [44] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [44] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [44] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [44] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-30-2019 16:30:32 OpenIddict.Validation.OpenIddictValidationHandler [44] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:24 OpenIddict.Validation.OpenIddictValidationHandler [55] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:24 OpenIddict.Validation.OpenIddictValidationHandler [55] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:24 OpenIddict.Validation.OpenIddictValidationHandler [55] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:24 OpenIddict.Validation.OpenIddictValidationHandler [55] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:24 OpenIddict.Validation.OpenIddictValidationHandler [55] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:24 OpenIddict.Validation.OpenIddictValidationHandler [55] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:24 OpenIddict.Validation.OpenIddictValidationHandler [55] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:24 OpenIddict.Validation.OpenIddictValidationHandler [55] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:24 OpenIddict.Validation.OpenIddictValidationHandler [55] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:24 OpenIddict.Validation.OpenIddictValidationHandler [55] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:24 OpenIddict.Validation.OpenIddictValidationHandler [55] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:26 OpenIddict.Validation.OpenIddictValidationHandler [50] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:26 OpenIddict.Validation.OpenIddictValidationHandler [50] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:26 OpenIddict.Validation.OpenIddictValidationHandler [50] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:26 OpenIddict.Validation.OpenIddictValidationHandler [50] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:26 OpenIddict.Validation.OpenIddictValidationHandler [50] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:26 OpenIddict.Validation.OpenIddictValidationHandler [50] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:26 OpenIddict.Validation.OpenIddictValidationHandler [50] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:26 OpenIddict.Validation.OpenIddictValidationHandler [50] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:26 OpenIddict.Validation.OpenIddictValidationHandler [50] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:26 OpenIddict.Validation.OpenIddictValidationHandler [50] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:26 OpenIddict.Validation.OpenIddictValidationHandler [50] - AuthenticationScheme: Bearer was successfully authenticated. 
DEBUG 19-47-2019 16:47:26 OpenIddict.Validation.OpenIddictValidationHandler [50] - AuthenticationScheme: Bearer was successfully authenticated. 
